### ISSUE TITLE
does this really work?

### ISSUE THREAD

**Issue by TomzBench** [fritzone/obfy#23]
Just curious about the concept in general.

If a solution to the problem is open source (like this).  Can't a cracker just check if this method is being used and detect it by observing the binary patterns created by this solution? 

I'm not sophisticated enough at RE to know if this is feasible. but conceptually it seems like their is no real solution to the problem still.

you know, obscurity is not security camp kind of thing. Especially if your solution is open source i feel like look else where for the solution or copy the ideas here but implement it yourself so that its signatures are unique.

**Comment by fritzone** [comment]
Well, eight years ago, when I wrote it, the compilers were not as clever as today. Those days you really could fool them with a cleverly placed volatile and some indirections, and to serve this purpose they indeed have generated huge amounts of code for you. Sadly (at least for this piece of software) in recent years the compilers got a lot more advanced, with optimizations that are somewhat beyond what one could expect and they have simply outgrown this, so unless you place in some compiler specific "do not optimize this code" instructions, the obscurities programmed into this library will be overlooked behind the wall of the mighty optimizer... who just does his job.

But back to answering your question: I have got no complaints till now that it does not work... I just assume that if you are a reverse engineer, determined to reverse everything they can their hands on, and say yes, you will reverse engineer it just because it's a challenge. In this case, it doesn't really work... However if you are the type that looks at the sheer size of extra code that it generates and says.. well, I'm not wasting my time with it, I'd rather have a beer and go back and reverse engineer C# code... then it works. It all depends who is the target reverse engineer.
