### ISSUE TITLE
VMProtect/Themida virtualization

### ISSUE THREAD

**Issue by ghost** [fritzone/obfy#6]
it is supported?

**Comment by fritzone** [comment]
No, they are not supported in the current release.

**Comment by ghost** [comment]
@fritzone maybe add bindings?

**Comment by fritzone** [comment]
I'm afraid that won't be possible, due to the fact that Themida and VMProtect work at a different level of abstraction. From what I understood from their site and after doing a quick check-out of their products, their applications (you have to pay for) are designed to protect windows based software, which is already compiled into an executable format, and they do not expose any APIs or libraries to offer a meddling point into the internals of the functionality of the software. The obfy framework on the other end works at source level, ie. you have to write actual code using the provided macro framework, it's platform independent, it needs to be compiled and is open source. The only way I can see these two parties interact with each other is that you take the executable you have compiled using the obfy framework and run it through Themida/VMProtect.

**Comment by ghost** [comment]
@fritzone ur see macros VMProtectSDK.h?
